<?php
/**
 * Implements hook_menu().
 * @return array
 */
function ctools_box_menu() {
  return array(
    'admin/config/media/ctools_box' => array(
      'title' => 'Ctools Box',
      'description' => 'Set image class',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ctools_box_admin_form'),
      'access arguments' => array('administer modules'),
    ),
  );
}

/**
 * Form callback for admin/config/media/ctools_box.
 * @param $form
 * @param $form_state
 * @return mixed
 */
function ctools_box_admin_form($form, &$form_state) {
  $form['ctools_box_image_class'] = array(
    '#type' => 'textfield',
    '#title' => t('Set image class'),
    '#description' => t('All images that have this class will be opened in a popup window.'),
    '#default_value' => variable_get('ctools_box_image_class', 'ctools-box'),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

/**
 * Implements hook_preprocess_image_style().
 * @param $vars
 */
function ctools_box_preprocess_image_style(&$vars) {
  $class = variable_get('ctools_box_image_class', 'ctools-box');
  if (isset($vars['attributes']['class'])) {
    $vars['attributes']['class'][] = $class;
  }
  else {
    $vars['attributes']['class'] = array($class);
  }
  $url = image_style_url('ctools_box_popup_large', $vars['path']);
  $vars['attributes']['data-large-image'] = $url;
}

/**
 * Implements hook_preprocess_page().
 * @param $vars
 */
function ctools_box_preprocess_page($vars) {
  $class = variable_get('ctools_box_image_class', 'ctools-box');
  drupal_add_js(array('ctoolsBoxImageClass' => $class), 'setting');
  drupal_add_js(drupal_get_path('module', 'ctools_box') . '/js/ctools_box.js');

  /* Ctools modal stuff. */
  ctools_include('modal');
  ctools_modal_add_js();
  /* Modal window settings. */
  $window_settings = array(
    'ctools_box_modal_window' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 960,
        'height' => 600,
      ),
      'animation' => 'fadeIn',
      'animationSpeed' => 'slow',
    ),
  );
  drupal_add_js($window_settings, 'setting');
}