<?php
/**
 * @file
 * Code for the Ctools Box module.
 */

/**
 * Implements hook_menu().
 * @return array
 */
function ctools_box_hook_menu() {
  return array(
    'ctools_box/%ctools_js/%' => array(
      'title' => 'Ctools Box Modal',
      'page arguments' => args(1, 2),
      'page callback' => 'ctools_box_modal_page',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

function ctools_box_modal_page($arg1 = NULL, $arg2 = NULL) {
  
}